<?php

namespace App\Domain\Teachers\Providers;

use App\Domain\Teachers\Contract\TeacherRepositoryInterface;
use App\Domain\Teachers\Repositories\TeacherRepository;
use Illuminate\Support\ServiceProvider;

class TeacherServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind(TeacherRepositoryInterface::class,TeacherRepository::class);
    }
}
